In [1]:
import pandas as pd

df = pd.read_csv("../../../Data/Question-Answer.csv").sample(500)
df.drop(columns=['distractor'],inplace=True)
df

,question,answer_text
20799,Why did Sue come up to the instructor 's family ?,To have a chat with the couple .
15226,What 's the main idea of the passage ?,An endangered language is spoken by only two p...
12458,What 's the best title for the text ?,Lunches packed with love .
22099,The best title of the passage is,Passing help
27284,What would be the best title for the text ?,An Unusual Architect -- Ieoh Ming Pei
...,...,...
30757,What did Rohm do when she saw the two boys ?,She asked them to ask their parents for help .
11029,We can learn from the passage that,the girl has played ping - pong many times
27722,Hybrid cars consume less energy than conventio...,have electric power to assist when needed
22967,The title of the passage should be,Short stature and short life
16631,Which of the following is NOT ture about Edwar...,He ran himself into exhaustion delivering pape...

# 1. Tokenization

In [2]:
def clean_sentence(text):
    return (
        text
        .replace("?","")
        .replace("!","")
        .replace("'","")
        .replace(",","")
        .replace(".","")
        .replace(":","")
        .replace("(","")
        .replace(")","")
    )

In [3]:
clean_sentence("What can we learn about Friends")

'What can we learn about Friends'

In [4]:
document = []
def text_document(row):
    question = clean_sentence(row['question'])
    answer = clean_sentence(row['answer_text'])
    
    merge_tokens = question + answer
    
    document.append(merge_tokens)

In [5]:
df.apply(text_document, axis=1)
document

['Why did Sue come up to the instructor s family To have a chat with the couple ',
 'What s the main idea of the passage An endangered language is spoken by only two people ',
 'What s the best title for the text Lunches packed with love ',
 'The best title   of the passage isPassing help',
 'What would be the best title for the text An Unusual Architect -- Ieoh Ming Pei',
 'What do we know about Reading Recovery Children on the project showed noticeable progress in reading ',
 'What does Helen do when she is with Betty Talk about her baby sister',
 'The writer probably agrees thatyou should consider others  response before you act assertively',
 'The passage is mainly aboutthe effects of the nuclear radiation leaks',
 'What s the best title for the text Grandpa s Birdhouses',
 'What s Whitney Houston s most outstanding achievements Her record - setting string of seven Number One singles ',
 'What s the name of the new picture book that recaptures the capital s Lunar New Year traditions for children Spring Festival in Beijing',
 'Why are Bollywood films often called " masala " films They mix different styles of movies ',
 'What s the purpose of the study that was carried out by Glass and her partners To study if cigarette smoking can cause the cognitive deficits among alcoholics ',
 'A possible reason for workers  unwillingness   to accept more leisure is thatthey will earn less money',
 'How did the students perform in the experiment The ones who encouraged themselves by writing in the second - person were better ',
 'The passage is mainly aboutAll of the above   ',
 'What can we infer from the passage women wore rings thousands of years earlier than men ',
 'Which of the following is TRUE Legionnaire s disease is only one of the results of " sick buildings " ',
 'What have researchers found out about the influence of parents and the school on children s intelligence Parents and the school have the equal power ',
 'Why is online education a perfect choice for a young stay - at - home mother She can learn while taking care of her family ',
 'Which of the following might be the best title for the passage US Military Plans',
 'The key to effective reading isto be motivated to read',
 'What can we learn from this story It s necessary to live with some difficulties ',
 'Microsoft grew at a time whenPersonal Computers were on every desk and in every home',
 'What can we know about the earlier credit cards from the passage Customers had to pay for things in full ',
 'Why does warm water freeze first in the same freezing weather Because some of the warm water turns to vapor  the amount   becomes less than that of cold water ',
 'What happened when the writer was talking on the phone The cat walked over his shirt ',
 'Which of the following is NOT a problem with the traditional flush toilet They are too complicated to use ',
 'Which of the following is NOT a speculation about Bryant s motive to change his number He wants to show that he is man of great importance ',
 'There is much pollution in the air today becausepeople drive big cars',
 'Why do the dolphins jump out of the water when they hear a whistle noise Because they want to get a fish as a prize ',
 'According to the passage  which of the following happens that you may not turn to the counsellors You are too poor to go to school ',
 'In the afternoons the woman walked three miles to her husband s work place towait for her husband',
 'The website and the consumer campaigner joined toappeal for the curriculum of financial education',
 'The same dream of the group of senior high school students is toto play in the NBA',
 'What would be introduced following the passage The other admission principle ',
 'What can we learn from what Dr Archana Singh Manoux said It is difficult for most British people to have a Mediterranean diet ',
 'For a healthier life  the author s suggestion is toeat less heavily salted food',
 'Many tours are timed for people toenjoy the fantastic eruption against the darkening sky',
 'Who are the intended readers of this passage General people ',
 'Mrs Matthews felt unhappy on the bus becauseshe felt she was now an old woman',
 'What purpose did Amy have when she began making Comfort Capes for sick children To make them happy and fearless ',
 'Why did nt Li Feng give up the plane Because the fighter was not totally out of control ',
 'Which is the best title of the article London',
 'From the passage  we knowbusy streets are not good places for running',
 'Mrs Badman described Paige as " being on death row " becausePaige could die at any time without warning',
 'What does the text mainly talk about More and more US students choose colleges overseas ',
 'According to the passage  what might cause children s inactivity A shrinking of the green',
 'What does Mrs Brown usually do at six fifty She has breakfast ',
 'By saying " miracle after miracle "  Shelli means thatit really surprised her that she survived so many operations',
 'Which air crash resulted from terrorist attack Pan Am Flight 103',
 'What does the article mainly talk about A Chinese girl s culture shock experience in the US ',
 'For the couple  among all the household duties  the most important isthe work of taking care of Lopsy',
 'Which of the following about train - spotters is true according to the passage They keep a careful path of every train ',
 'What s the difference between novels and short stories Short stories are more perfect and difficult than novels ',
 'From the passage we can learn thatFrance does successfully in controlling road accidents',
 'When I was walking in the street a young man said sorry to me for touching my bag',
 'Which of the following is true according to the passage People s traditional concepts about jobs need changing ',
 'At the beginning of his organization things did nt go on smoothly',
 'People all over the world enjoy sports becauseall of the above',
 'By doing mouse experiments  the scientistsfound each smell creates a similar pattern of active cells in different mice',
 'In Damien s apartment  people ca ntwear shoes',
 'People like to choose cruises     because it is a new attempt for them',
 'The aim of the study in theJournal of the American Geriatrics Societyisto see whether people s personality affects their life span',
 'When the writer was allowed to enter the only key school in his hometown his mother did nt say a word but to cry',
 'According to the passage  which of the following is TRUE Deng left school in1919 ',
 'Which of the following statement is TRUE Javier faced a number of challenges that put him at some risks ',
 'What do we learn from the story When people get on well  they feel happy ',
 'What does this passage mainly tell us High fuel prices  influences on school buses ',
 'What problems can a casual dress code cause according to the passage Sometimes employees dress too casually ',
 'Mrs McCullers did not write for many years becauseshe had a mental block',
 'According to the text  San Francisco city officialsare aware of the app s disadvantages',
 'What will make one man happy may not make another man happy  This sentence means "  Different peolpe hold different opinions about happiness',
 'Douglas drew an empty hand in order toshow thanks to his teacher',
 'We can infer from the passage thatwinning a bid is not just a matter of luck',
 'When Kyle MacDonald started his Internet bartering  hedid nt expect anyone to give him a house for a paper clip',
 'What can we learn from the article Puppy love will be bad for student s study ',
 'The best title for this passage should be " " What We Should Do in Earthquakes',
 'What s special about dime stores They sell lots of goods at a small profit ',
 'The text is mainly aboutphone card collecting as a hobby',
 'What s the best title of the passage A small Teng from Thailand -- Viseskul',
 'What do we know about Laurel Acres  compared with the other parks It attracts the largest number of visitors ',
 'What s the best title for the text Pay to play---- Should college athletes be paid ',
 'The experiments proved thatmothers of premature babies do not have the instinct to hold their babies on the left',
 'Some parents pay their children for doing housework becausethey want their children to learn how to make money for themselves',
 'The following is true EXCEPTthe reporter knew the way to find out who was the most important ',
 'What s the best title for the passage Welcome Back  Discovery',
 'Who took the jewelry The thief ',
 'Mandela s hobbies on Robben Island weregardening and tennis',
 'What do we know about Relay for Life It is held for a whole day without a break ',
 'From the passage we know that most children enjoyplaying computer games',
 'What will happen in the eighth week The marriage will come to the breaking point ',
 'Doctors were worried about using TXA because    they had nt used it on accident victims before',
 'What would be the best title for the passage Grandma Moses and Painting',
 'An important difference between PEEL and non - PEEL classes is that in the PEEL classesmore attention is paid to the students  own ideas',
 'Which is NOT the advantage of the device it held only twenty doses of medicine ',
 'What s the best title of this article Father and child bonding is very important',
 'The serious effects of the death of languages include all except thatLanguage diversity would become an obstacle to globalization',
 'What is an ion according to the passage It s a charged particle ',
 'Which of the following statements is TRUE Global warm is putting animals and humans at risk ',
 'Why did the author use to take freeways to her parents  home It would be faster and easier ',
 'Mrs Lin wanted to buy a new dress  Her husband suggested that she buy it from a shop near their home  Mrs Lin disagreed because she had been cheated by that shop  So she said  " I wo nt go there again because   once bitten  twice shy',
 'It can be inferred from the passage thatthe 60 patients all have physical and psychological problems',
 'According to James Brown  which of the following types of person is more likely to be pickpocketed People who are absent - minded ',
 'According to the passage  people choose to be vegetarians for the following reasons EXCEPTthey live in areas where meat supply is not adequate',
 'The author implies that it is very easy to enter a bookshop and buya book that unexpectedly fascinates you',
 'Which of the following is NOT true about Chinese people     Many Chinese like to go to Southeast Asia in winter for sightseeing ',
 'The writer mainly wants to tell usseveral ways for audience to discover the fun of the Spring Festival Gala',
 'What did the writer do after following the plan He contacted his old friends ',
 'What is the best title of the passage London s green games',
 'How did Jimmy feel on hearing the interviewer s question There was no hope for him to get the job ',
 'What can we learn about friendship  according Friends in childhood are sometimes forgotten by bus ',
 'The book"The Second Stage"was about the condition of the women s movement then',
 'Which is the best title of this passage Some Tips on How to Talk with Parents',
 'Which of the following students is most likely to be focused A standing boy who is faced with stress',
 'The following statements are all right exceptI write some encouraging words on the food',
 'According to the passage  the term " photographic memory " is used tostress that a person has a very good memory',
 'Why did the town people regard the monkey as something frightening He did something that upset the people s lives ',
 'What is the main reason for a celebrity s opting for cosmetic surgery The celebrity wants to be younger  prettier  and thinner ',
 'What was suggested about the construction of a new city at sea The building of the city would rest on a floating island ',
 'What s the advice given by a teacher in Caracas to her students Washing your hair quite often ',
 'This passage mainly talks abouta survey about teenagerstop 10 heroes',
 'The study was carried out by analyzingvolunteers  reactions to horrible pictures and data from their brain scans',
 'Why did the author help the young man pay for the gas She had learned something from the farmer ',
 'The clerk didn  t want to exchange the stove for I m a becauseI m a didn  t have the receipt',
 'Which of the following is NOT true The Center is run by the government ',
 'What does the passage mainly talk about Asian tsunami kills many people  and many more become homeless ',
 'The writer used a lot of questions at the beginning tolead into the topic of the passage',
 'EO-1 takes photographs of the same places as Landsat becausethe two groups of pictures can show the changes of Earth',
 'What presents can you take to your dinner hostess in Germany Flowers except red roses',
 'On the third day after being taken to the hospital the situation of the author s son suddenly worsened',
 'Mr Baker tried his best to catch the horse tobeat it up',
 'What can we learn about sitting People usually have to sit for a long time nowadays ',
 'What is the best title for this passage The Poor Suffer from High Food Prices ',
 'What does Christmas Eve mean to the 14 Tsinghua students Showing care to the beggars and the homeless ',
 'According to the passage people have always found trees useful',
 'What is the main idea of the passage It s time to be stricter with our kids ',
 'Frito - Lay s executives claim that the promoting of American food in the international marketwill be in the interest of the local people',
 'What gave Khan the idea of teaching math online His success in helping his cousin learn math ',
 'It can be inferred from the passage thatsome school staff will say " No " to the plans for a shorter summer holiday',
 'What s the text mainly about Ecotourism could endanger the survival of the wildlife people want to see ',
 'The passage is mainly concerned withcross - channel ferries',
 'Which of the following activities is NOT a creative one according to the passage To buy some books from a bookstore ',
 'The " freshman fifteen " isweight that first - year university students can gain',
 'According to Brian Tong  why may people prefer the iPad Mini to the Google Nexus 7 Because it has more functions ',
 'Why did the author carry out the survey To inform people of different steamers',
 'The purpose of the passage is tohighlight the contributions of other staff at school besides teachers ',
 'What causes advances in technology according to Dr Silva Great changes in people s way of life ',
 'According to the passage  a vertical farmis planted on levels upwards',
 'What problem did Millie have at the beginning of the story She did nt know how to start jumping with a long rope ',
 'The main idea of the passage isOPEC will not increase oil production to make up the shortfall caused by Iraq',
 'Which of the following is TRUE The Kurzweil machine can help blind people and short - sighted children ',
 'This passage is mainly aboutthe event that police cleared Hong Kong protest sites',
 'In the passage " labor force " is defined aspeople who are available to work and earn income',
 'We know from the text that Watsonlived a very long life',
 'From the text we can learn thatone should respect others no matter who they are',
 'The main idea of this passage isto introduce different forms of pollution and ways to control it',
 'According to the passage  branded stationsoffer a steady oil supply',
 'What do we know about Tom He was seriously ill ',
 'What can we know about " self - driving " chairs from the text They are the inventions of a car company ',
 'Which of the following is TRUE Teachers may not like the program ',
 'What s the main idea of this passage Despite the dissatisfactions with college  most Americans still favor college education',
 'Who gets very angry Sam ',
 'From the passage we can know thatJune was poor when she was young',
 'What would be the best title for the passage Learning to Get Back Up ',
 'The passage was intended forgeneral readers',
 'What might the author most probably continue to talk about in the following passage What one should avoid in building self - confidence ',
 'What does the passage mainly tell us Something interesting about dogs ',
 'Why does a couch - potato look like a real potato  Because he or shealmost never moves while watching TV and gets very fat',
 'PAMS is organized with the purpose ofoffering medical treatment and education to towns in Peru',
 'Dr Haydon asked Dr Eyck to come to Clens Falls becauseThe boy needed the help of a surgeon',
 'After the students use the toilets  they shouldclean them and wash their hands',
 'Which of the following is NOT a benefit the students get from Andrea Peterson s class Prizes for English and maths ',
 'What is the feature of Art Gallery of Ontario You can see art exhibits and collections from around the world  ',
 'Why does Siddiqui say the case of the sleepwalking woman is unique The sleepwalking woman took a lot of complex actions ',
 'What s the best title of the passage Changes of America s Golden Dream',
 'Maybe you do nt want to make friends with a person who sleeps cured up  Why  He or she   would rather be alone than communicate with you',
 'What we should do to have friends according to the author All the above ',
 'Daniel Burd won first prize at the Canada - Wide Science Fair becausehe found a way to degrade plastics in shorter time',
 'Which of the following would be the best title of the passage The value of life ',
 'Which kind of voluntary work does nt require special experience or skills Tree Nursery Volunteer ',
 'In Dennis Garrity s opinion    government should support farmers in planting and protecting trees',
 'Writing this passage  the writer s main purpose is tointroduce foreign accent syndrome and some related information',
 'Why did the writer think scientific research to be one of the best things You may continue doing with something different and exciting  so you can never be tired of doing the scientific research ',
 'Which of the following statements is true according to the passage To make money is the root of developers working on new games ',
 'According to the passage  which of the following is friendly You ve got a great personality ',
 'The passage     is mainly   aboutroads of the future',
 'Why does the writer say that women and beauty go together Because women try to keep their beauty by dressing up ',
 'What s the danger of space junk It will hit a spaceship ',
 'According to the passage  we can learn thatless use of a part of the body will become weaker',
 'In the second shopthey find a sweater of the right size and colour',
 'In " Dream World Cup "  the children drew the flags of some countriesto show their good wishes for the football teams',
 'The best title for this passage isGood study habits',
 'We can learn from the text that Artemisinin has a good effect oncuring patients suffering from malaria ',
 'It can be inferred from the passage thatFran Tarkenton might not take a risk in blocking again',
 'The proper way to express your dissatisfaction with your best friend is togo to your friend and let him know your dissatisfaction',
 'Which of the following is not allowed in Britain Children of about 15 drinking in a pub with adults ',
 'What will the passage most probably talk about next Take some measures to protect your eyes while skiing in new snow areas ',
 'Which is TRUE according to the passage All of the above ',
 'What s the meaning of "  Some children ca nt remember what their parents look like ',
 'Which of the following can be the best title for the passage Take Your Dog to Work Day',
 'Which of the following facts most probably helps McManus and her team in identifying the origin of stones Gemstones from the same area produce similar light patterns ',

# 2. Build vocab

In [6]:
vocab = {
    "UNK":0
}

In [7]:
from nltk.tokenize import word_tokenize
for sentence in document:
    tokenized_word = word_tokenize(sentence)
    for token in tokenized_word:
        if token not in vocab:
            vocab[token] = len(vocab)

In [8]:
print(len(vocab))
vocab

2420

{'UNK': 0,
 'Why': 1,
 'did': 2,
 'Sue': 3,
 'come': 4,
 'up': 5,
 'to': 6,
 'the': 7,
 'instructor': 8,
 's': 9,
 'family': 10,
 'To': 11,
 'have': 12,
 'a': 13,
 'chat': 14,
 'with': 15,
 'couple': 16,
 'What': 17,
 'main': 18,
 'idea': 19,
 'of': 20,
 'passage': 21,
 'An': 22,
 'endangered': 23,
 'language': 24,
 'is': 25,
 'spoken': 26,
 'by': 27,
 'only': 28,
 'two': 29,
 'people': 30,
 'best': 31,
 'title': 32,
 'for': 33,
 'text': 34,
 'Lunches': 35,
 'packed': 36,
 'love': 37,
 'The': 38,
 'isPassing': 39,
 'help': 40,
 'would': 41,
 'be': 42,
 'Unusual': 43,
 'Architect': 44,
 '--': 45,
 'Ieoh': 46,
 'Ming': 47,
 'Pei': 48,
 'do': 49,
 'we': 50,
 'know': 51,
 'about': 52,
 'Reading': 53,
 'Recovery': 54,
 'Children': 55,
 'on': 56,
 'project': 57,
 'showed': 58,
 'noticeable': 59,
 'progress': 60,
 'in': 61,
 'reading': 62,
 'does': 63,
 'Helen': 64,
 'when': 65,
 'she': 66,
 'Betty': 67,
 'Talk': 68,
 'her': 69,
 'baby': 70,
 'sister': 71,
 'writer': 72,
 'probably': 73,
 'agrees': 74,
 'thatyou': 75,
 'should': 76,
 'consider': 77,
 'others': 78,
 'response': 79,
 'before': 80,
 'you': 81,
 'act': 82,
 'assertively': 83,
 'mainly': 84,
 'aboutthe': 85,
 'effects': 86,
 'nuclear': 87,
 'radiation': 88,
 'leaks': 89,
 'Grandpa': 90,
 'Birdhouses': 91,
 'Whitney': 92,
 'Houston': 93,
 'most': 94,
 'outstanding': 95,
 'achievements': 96,
 'Her': 97,
 'record': 98,
 '-': 99,
 'setting': 100,
 'string': 101,
 'seven': 102,
 'Number': 103,
 'One': 104,
 'singles': 105,
 'name': 106,
 'new': 107,
 'picture': 108,
 'book': 109,
 'that': 110,
 'recaptures': 111,
 'capital': 112,
 'Lunar': 113,
 'New': 114,
 'Year': 115,
 'traditions': 116,
 'children': 117,
 'Spring': 118,
 'Festival': 119,
 'Beijing': 120,
 'are': 121,
 'Bollywood': 122,
 'films': 123,
 'often': 124,
 'called': 125,
 '``': 126,
 'masala': 127,
 'They': 128,
 'mix': 129,
 'different': 130,
 'styles': 131,
 'movies': 132,
 'purpose': 133,
 'study': 134,
 'was': 135,
 'carried': 136,
 'out': 137,
 'Glass': 138,
 'and': 139,
 'partners': 140,
 'if': 141,
 'cigarette': 142,
 'smoking': 143,
 'can': 144,
 'cause': 145,
 'cognitive': 146,
 'deficits': 147,
 'among': 148,
 'alcoholics': 149,
 'A': 150,
 'possible': 151,
 'reason': 152,
 'workers': 153,
 'unwillingness': 154,
 'accept': 155,
 'more': 156,
 'leisure': 157,
 'thatthey': 158,
 'will': 159,
 'earn': 160,
 'less': 161,
 'money': 162,
 'How': 163,
 'students': 164,
 'perform': 165,
 'experiment': 166,
 'ones': 167,
 'who': 168,
 'encouraged': 169,
 'themselves': 170,
 'writing': 171,
 'second': 172,
 'person': 173,
 'were': 174,
 'better': 175,
 'aboutAll': 176,
 'above': 177,
 'infer': 178,
 'from': 179,
 'women': 180,
 'wore': 181,
 'rings': 182,
 'thousands': 183,
 'years': 184,
 'earlier': 185,
 'than': 186,
 'men': 187,
 'Which': 188,
 'following': 189,
 'TRUE': 190,
 'Legionnaire': 191,
 'disease': 192,
 'one': 193,
 'results': 194,
 'sick': 195,
 'buildings': 196,
 'researchers': 197,
 'found': 198,
 'influence': 199,
 'parents': 200,
 'school': 201,
 'intelligence': 202,
 'Parents': 203,
 'equal': 204,
 'power': 205,
 'online': 206,
 'education': 207,
 'perfect': 208,
 'choice': 209,
 'young': 210,
 'stay': 211,
 'at': 212,
 'home': 213,
 'mother': 214,
 'She': 215,
 'learn': 216,
 'while': 217,
 'taking': 218,
 'care': 219,
 'might': 220,
 'US': 221,
 'Military': 222,
 'Plans': 223,
 'key': 224,
 'effective': 225,
 'isto': 226,
 'motivated': 227,
 'read': 228,
 'this': 229,
 'story': 230,
 'It': 231,
 'necessary': 232,
 'live': 233,
 'some': 234,
 'difficulties': 235,
 'Microsoft': 236,
 'grew': 237,
 'time': 238,
 'whenPersonal': 239,
 'Computers': 240,
 'every': 241,
 'desk': 242,
 'credit': 243,
 'cards': 244,
 'Customers': 245,
 'had': 246,
 'pay': 247,
 'things': 248,
 'full': 249,
 'warm': 250,
 'water': 251,
 'freeze': 252,
 'first': 253,
 'same': 254,
 'freezing': 255,
 'weather': 256,
 'Because': 257,
 'turns': 258,
 'vapor': 259,
 'amount': 260,
 'becomes': 261,
 'cold': 262,
 'happened': 263,
 'talking': 264,
 'phone': 265,
 'cat': 266,
 'walked': 267,
 'over': 268,
 'his': 269,
 'shirt': 270,
 'NOT': 271,
 'problem': 272,
 'traditional': 273,
 'flush': 274,
 'toilet': 275,
 'too': 276,
 'complicated': 277,
 'use': 278,
 'speculation': 279,
 'Bryant': 280,
 'motive': 281,
 'change': 282,
 'number': 283,
 'He': 284,
 'wants': 285,
 'show': 286,
 'he': 287,
 'man': 288,
 'great': 289,
 'importance': 290,
 'There': 291,
 'much': 292,
 'pollution': 293,
 'air': 294,
 'today': 295,
 'becausepeople': 296,
 'drive': 297,
 'big': 298,
 'cars': 299,
 'dolphins': 300,
 'jump': 301,
 'they': 302,
 'hear': 303,
 'whistle': 304,
 'noise': 305,
 'want': 306,
 'get': 307,
 'fish': 308,
 'as': 309,
 'prize': 310,
 'According': 311,
 'which': 312,
 'happens': 313,
 'may': 314,
 'not': 315,
 'turn': 316,
 'counsellors': 317,
 'You': 318,
 'poor': 319,
 'go': 320,
 'In': 321,
 'afternoons': 322,
 'woman': 323,
 'three': 324,
 'miles': 325,
 'husband': 326,
 'work': 327,
 'place': 328,
 'towait': 329,
 'website': 330,
 'consumer': 331,
 'campaigner': 332,
 'joined': 333,
 'toappeal': 334,
 'curriculum': 335,
 'financial': 336,
 'dream': 337,
 'group': 338,
 'senior': 339,
 'high': 340,
 'toto': 341,
 'play': 342,
 'NBA': 343,
 'introduced': 344,
 'other': 345,
 'admission': 346,
 'principle': 347,
 'what': 348,
 'Dr': 349,
 'Archana': 350,
 'Singh': 351,
 'Manoux': 352,
 'said': 353,
 'difficult': 354,
 'British': 355,
 'Mediterranean': 356,
 'diet': 357,
 'For': 358,
 'healthier': 359,
 'life': 360,
 'author': 361,
 'suggestion': 362,
 'toeat': 363,
 'heavily': 364,
 'salted': 365,
 'food': 366,
 'Many': 367,
 'tours': 368,
 'timed': 369,
 'toenjoy': 370,
 'fantastic': 371,
 'eruption': 372,
 'against': 373,
 'darkening': 374,
 'sky': 375,
 'Who': 376,
 'intended': 377,
 'readers': 378,
 'General': 379,
 'Mrs': 380,
 'Matthews': 381,
 'felt': 382,
 'unhappy': 383,
 'bus': 384,
 'becauseshe': 385,
 'now': 386,
 'an': 387,
 'old': 388,
 'Amy': 389,
 'began': 390,
 'making': 391,
 'Comfort': 392,
 'Capes': 393,
 'make': 394,
 'them': 395,
 'happy': 396,
 'fearless': 397,
 'nt': 398,
 'Li': 399,
 'Feng': 400,
 'give': 401,
 'plane': 402,
 'fighter': 403,
 'totally': 404,
 'control': 405,
 'article': 406,
 'London': 407,
 'From': 408,
 'knowbusy': 409,
 'streets': 410,
 'good': 411,
 'places': 412,
 'running': 413,
 'Badman': 414,
 'described': 415,
 'Paige': 416,
 'being': 417,
 'death': 418,
 'row': 419,
 'becausePaige': 420,
 'could': 421,
 'die': 422,
 'any': 423,
 'without': 424,
 'warning': 425,
 'talk': 426,
 'More': 427,
 'choose': 428,
 'colleges': 429,
 'overseas': 430,
 'inactivity': 431,
 'shrinking': 432,
 'green': 433,
 'Brown': 434,
 'usually': 435,
 'six': 436,
 'fifty': 437,
 'has': 438,
 'breakfast': 439,
 'By': 440,
 'saying': 441,
 'miracle': 442,
 'after': 443,
 'Shelli': 444,
 'means': 445,
 'thatit': 446,
 'really': 447,
 'surprised': 448,
 'survived': 449,
 'so': 450,
 'many': 451,
 'operations': 452,
 'crash': 453,
 'resulted': 454,
 'terrorist': 455,
 'attack': 456,
 'Pan': 457,
 'Am': 458,
 'Flight': 459,
 '103': 460,
 'Chinese': 461,
 'girl': 462,
 'culture': 463,
 'shock': 464,
 'experience': 465,
 'all': 466,
 'household': 467,
 'duties': 468,
 'important': 469,
 'isthe': 470,
 'Lopsy': 471,
 'train': 472,
 'spotters': 473,
 'true': 474,
 'according': 475,
 'keep': 476,
 'careful': 477,
 'path': 478,
 'difference': 479,
 'between': 480,
 'novels': 481,
 'short': 482,
 'stories': 483,
 'Short': 484,
 'thatFrance': 485,
 'successfully': 486,
 'controlling': 487,
 'road': 488,
 'accidents': 489,
 'When': 490,
 'I': 491,
 'walking': 492,
 'street': 493,
 'sorry': 494,
 'me': 495,
 'touching': 496,
 'my': 497,
 'bag': 498,
 'People': 499,
 'concepts': 500,
 'jobs': 501,
 'need': 502,
 'changing': 503,
 'At': 504,
 'beginning': 505,
 'organization': 506,
 'smoothly': 507,
 'world': 508,
 'enjoy': 509,
 'sports': 510,
 'becauseall': 511,
 'doing': 512,
 'mouse': 513,
 'experiments': 514,
 'scientistsfound': 515,
 'each': 516,
 'smell': 517,
 'creates': 518,
 'similar': 519,
 'pattern': 520,
 'active': 521,
 'cells': 522,
 'mice': 523,
 'Damien': 524,
 'apartment': 525,
 'ca': 526,
 'ntwear': 527,
 'shoes': 528,
 'like': 529,
 'cruises': 530,
 'because': 531,
 'it': 532,
 'attempt': 533,
 'aim': 534,
 'theJournal': 535,
 'American': 536,
 'Geriatrics': 537,
 'Societyisto': 538,
 'see': 539,
 'whether': 540,
 'personality': 541,
 'affects': 542,
 'their': 543,
 'span': 544,
 'allowed': 545,
 'enter': 546,
 'hometown': 547,
 'say': 548,
 'word': 549,
 'but': 550,
 'cry': 551,
 'Deng': 552,
 'left': 553,
 'in1919': 554,
 'statement': 555,
 'Javier': 556,
 'faced': 557,
 'challenges': 558,
 'put': 559,
 'him': 560,
 'risks': 561,
 'well': 562,
 'feel': 563,
 'tell': 564,
 'us': 565,
 'High': 566,
 'fuel': 567,
 'prices': 568,
 'influences': 569,
 'buses': 570,
 'problems': 571,
 'casual': 572,
 'dress': 573,
 'code': 574,
 'Sometimes': 575,
 'employees': 576,
 'casually': 577,
 'McCullers': 578,
 'write': 579,
 'mental': 580,
 'block': 581,
 'San': 582,
 'Francisco': 583,
 'city': 584,
 'officialsare': 585,
 'aware': 586,
 'app': 587,
 'disadvantages': 588,
 'another': 589,
 'This': 590,
 'sentence': 591,
 'Different': 592,
 'peolpe': 593,
 'hold': 594,
 'opinions': 595,
 'happiness': 596,
 'Douglas': 597,
 'drew': 598,
 'empty': 599,
 'hand': 600,
 'order': 601,
 'toshow': 602,
 'thanks': 603,
 'teacher': 604,
 'We': 605,
 'thatwinning': 606,
 'bid': 607,
 'just': 608,
 'matter': 609,
 'luck': 610,
 'Kyle': 611,
 'MacDonald': 612,
 'started': 613,
 'Internet': 614,
 'bartering': 615,
 'hedid': 616,
 'expect': 617,
 'anyone': 618,
 'house': 619,
 'paper': 620,
 'clip': 621,
 'Puppy': 622,
 'bad': 623,
 'student': 624,
 'Should': 625,
 'Do': 626,
 'Earthquakes': 627,
 'special': 628,
 'dime': 629,
 'stores': 630,
 'sell': 631,
 'lots': 632,
 'goods': 633,
 'small': 634,
 'profit': 635,
 'aboutphone': 636,
 'card': 637,
 'collecting': 638,
 'hobby': 639,
 'Teng': 640,
 'Thailand': 641,
 'Viseskul': 642,
 'Laurel': 643,
 'Acres': 644,
 'compared': 645,
 'parks': 646,
 'attracts': 647,
 'largest': 648,
 'visitors': 649,
 'Pay': 650,
 'college': 651,
 'athletes': 652,
 'paid': 653,
 'proved': 654,
 'thatmothers': 655,
 'premature': 656,
 'babies': 657,
 'instinct': 658,
 'Some': 659,
 'housework': 660,
 'becausethey': 661,
 'how': 662,
 'EXCEPTthe': 663,
 'reporter': 664,
 'knew': 665,
 'way': 666,
 'find': 667,
 'Welcome': 668,
 'Back': 669,
 'Discovery': 670,
 'took': 671,
 'jewelry': 672,
 'thief': 673,
 'Mandela': 674,
 'hobbies': 675,
 'Robben': 676,
 'Island': 677,
 'weregardening': 678,
 'tennis': 679,
 'Relay': 680,
 'Life': 681,
 'held': 682,
 'whole': 683,
 'day': 684,
 'break': 685,
 'enjoyplaying': 686,
 'computer': 687,
 'games': 688,
 'happen': 689,
 'eighth': 690,
 'week': 691,
 'marriage': 692,
 'breaking': 693,
 'point': 694,
 'Doctors': 695,
 'worried': 696,
 'using': 697,
 'TXA': 698,
 'used': 699,
 'accident': 700,
 'victims': 701,
 'Grandma': 702,
 'Moses': 703,
 'Painting': 704,
 'PEEL': 705,
 'non': 706,
 'classes': 707,
 'classesmore': 708,
 'attention': 709,
 'own': 710,
 'ideas': 711,
 'advantage': 712,
 'device': 713,
 'twenty': 714,
 'doses': 715,
 'medicine': 716,
 'Father': 717,
 'child': 718,
 'bonding': 719,
 'very': 720,
 'serious': 721,
 'languages': 722,
 'include': 723,
 'except': 724,
 'thatLanguage': 725,
 'diversity': 726,
 'become': 727,
 'obstacle': 728,
 'globalization': 729,
 'ion': 730,
 'charged': 731,
 'particle': 732,
 'statements': 733,
 'Global': 734,
 'putting': 735,
 'animals': 736,
 'humans': 737,
 'risk': 738,
 'take': 739,
 'freeways': 740,
 'faster': 741,
 'easier': 742,
 'Lin': 743,
 'wanted': 744,
 'buy': 745,
 'suggested': 746,
 'shop': 747,
 'near': 748,
 'disagreed': 749,
 'been': 750,
 'cheated': 751,
 'So': 752,
 'wo': 753,
 'there': 754,
 'again': 755,
 'once': 756,
 'bitten': 757,
 'twice': 758,
 'shy': 759,
 'inferred': 760,
 'thatthe': 761,
 '60': 762,
 'patients': 763,
 'physical': 764,
 'psychological': 765,
 'James': 766,
 'types': 767,
 'likely': 768,
 'pickpocketed': 769,
 'absent': 770,
 'minded': 771,
 'vegetarians': 772,
 'reasons': 773,
 'EXCEPTthey': 774,
 'areas': 775,
 'where': 776,
 'meat': 777,
 'supply': 778,
 'adequate': 779,
 'implies': 780,
 'easy': 781,
 'bookshop': 782,
 'buya': 783,
 'unexpectedly': 784,
 'fascinates': 785,
 'Southeast': 786,
 'Asia': 787,
 'winter': 788,
 'sightseeing': 789,
 'usseveral': 790,
 'ways': 791,
 'audience': 792,
 'discover': 793,
 'fun': 794,
 'Gala': 795,
 'plan': 796,
 'contacted': 797,
 'friends': 798,
 'Jimmy': 799,
 'hearing': 800,
 'interviewer': 801,
 'question': 802,
 'no': 803,
 'hope': 804,
 'job': 805,
 'friendship': 806,
 'Friends': 807,
 'childhood': 808,
 'sometimes': 809,
 'forgotten': 810,
 "''": 811,
 'Second': 812,
 'Stage': 813,
 'condition': 814,
 'movement': 815,
 'then': 816,
 'Tips': 817,
 'focused': 818,
 'standing': 819,
 'boy': 820,
 'stress': 821,
 'right': 822,
 'exceptI': 823,
 'encouraging': 824,
 'words': 825,
 'term': 826,
 'photographic': 827,
 'memory': 828,
 'tostress': 829,
 'town': 830,
 'regard': 831,
 'monkey': 832,
 'something': 833,
 'frightening': 834,
 'upset': 835,
 'lives': 836,
 'celebrity': 837,
 'opting': 838,
 'cosmetic': 839,
 'surgery': 840,
 'younger': 841,
 'prettier': 842,
 'thinner': 843,
 'construction': 844,
 'sea': 845,
 'building': 846,
 'rest': 847,
 'floating': 848,
 'island': 849,
 'advice': 850,
 'given': 851,
 'Caracas': 852,
 'Washing': 853,
 'your': 854,
 'hair': 855,
 'quite': 856,
 'talks': 857,
 'abouta': 858,
 'survey': 859,
 'teenagerstop': 860,
 '10': 861,
 'heroes': 862,
 'analyzingvolunteers': 863,
 'reactions': 864,
 'horrible': 865,
 'pictures': 866,
 'data': 867,
 'brain': 868,
 'scans': 869,
 'gas': 870,
 'learned': 871,
 'farmer': 872,
 'clerk': 873,
 'didn': 874,
 't': 875,
 'exchange': 876,
 'stove': 877,
 'm': 878,
 'becauseI': 879,
 'receipt': 880,
 'Center': 881,
 'run': 882,
 'government': 883,
 'Asian': 884,
 'tsunami': 885,
 'kills': 886,
 'homeless': 887,
 'lot': 888,
 'questions': 889,
 'tolead': 890,
 'into': 891,
 'topic': 892,
 'EO-1': 893,
 'takes': 894,
 'photographs': 895,
 'Landsat': 896,
 'becausethe': 897,
 'groups': 898,
 'changes': 899,
 'Earth': 900,
 'presents': 901,
 'dinner': 902,
 'hostess': 903,
 'Germany': 904,
 'Flowers': 905,
 'red': 906,
 'roses': 907,
 'On': 908,
 'third': 909,
 'taken': 910,
 'hospital': 911,
 'situation': 912,
 'son': 913,
 'suddenly': 914,
 'worsened': 915,
 'Mr': 916,
 'Baker': 917,
 'tried': 918,
 'catch': 919,
 'horse': 920,
 'tobeat': 921,
 'sitting': 922,
 'sit': 923,
 'long': 924,
 'nowadays': 925,
 'Poor': 926,
 'Suffer': 927,
 'Food': 928,
 'Prices': 929,
 'Christmas': 930,
 'Eve': 931,
 'mean': 932,
 '14': 933,
 'Tsinghua': 934,
 'Showing': 935,
 'beggars': 936,
 'always': 937,
 'trees': 938,
 'useful': 939,
 'stricter': 940,
 'our': 941,
 'kids': 942,
 'Frito': 943,
 'Lay': 944,
 'executives': 945,
 'claim': 946,
 'promoting': 947,
 'international': 948,
 'marketwill': 949,
 'interest': 950,
 'local': 951,
 'gave': 952,
 'Khan': 953,
 'teaching': 954,
 'math': 955,
 'His': 956,
 'success': 957,
 'helping': 958,
 'cousin': 959,
 'thatsome': 960,
 'staff': 961,
 'No': 962,
 'plans': 963,
 'shorter': 964,
 'summer': 965,
 'holiday': 966,
 'Ecotourism': 967,
 'endanger': 968,
 'survival': 969,
 'wildlife': 970,
 'concerned': 971,
 'withcross': 972,
 'channel': 973,
 'ferries': 974,
 'activities': 975,
 'creative': 976,
 'books': 977,
 'bookstore': 978,
 'freshman': 979,
 'fifteen': 980,
 'isweight': 981,
 'year': 982,
 'university': 983,
 'gain': 984,
 'Brian': 985,
 'Tong': 986,
 'why': 987,
 'prefer': 988,
 'iPad': 989,
 'Mini': 990,
 'Google': 991,
 'Nexus': 992,
 '7': 993,
 'functions': 994,
 'carry': 995,
 'inform': 996,
 'steamers': 997,
 'tohighlight': 998,
 'contributions': 999,
 ...}

# 3. Text to numeric representation

In [9]:
def line_to_numeric_rep(sentence, vocab):
    numerical_present = []
    for word in word_tokenize(sentence):
        if word in vocab:
            numerical_present.append(vocab[word])
        else:
            numerical_present.append(0)
    return numerical_present

In [10]:
line_to_numeric_rep("What can we learn about Friends",vocab)

[17, 144, 50, 216, 52, 807]

In [11]:
numerical_document = []
for sentence in document:
    numerical_document.append(line_to_numeric_rep(sentence,vocab))

numerical_document

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 16],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 [17, 9, 7, 31, 32, 33, 7, 34, 35, 36, 15, 37],
 [38, 31, 32, 20, 7, 21, 39, 40],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44, 45, 46, 47, 48],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58, 59, 60, 61, 62],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68, 52, 69, 70, 71],
 [38, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
 [38, 21, 25, 84, 85, 86, 20, 7, 87, 88, 89],
 [17, 9, 7, 31, 32, 33, 7, 34, 90, 9, 91],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20, 102, 103, 104, 105],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117,
  118,
  119,
  61,
  120],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129, 130, 131, 20, 132],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145,
  7,
  146,
  147,
  148,
  149],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25, 158, 159, 160, 161, 162],
 [163,
  2,
  7,
  164,
  165,
  61,
  7,
  166,
  38,
  167,
  168,
  169,
  170,
  27,
  171,
  61,
  7,
  172,
  99,
  173,
  174,
  175],
 [38, 21, 25, 84, 176, 20, 7, 177],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183, 20, 184, 185, 186, 187],
 [188,
  20,
  7,
  189,
  25,
  190,
  191,
  9,
  192,
  25,
  28,
  193,
  20,
  7,
  194,
  20,
  126,
  195,
  196,
  126],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7,
  201,
  12,
  7,
  204,
  205],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217,
  218,
  219,
  20,
  69,
  10],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33, 7, 21, 221, 222, 223],
 [38, 224, 6, 225, 62, 226, 42, 227, 6, 228],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232, 6, 233, 15, 234, 235],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241, 242, 139, 61, 241, 213],
 [17,
  144,
  50,
  51,
  52,
  7,
  185,
  243,
  244,
  179,
  7,
  21,
  245,
  246,
  6,
  247,
  33,
  248,
  61,
  249],
 [1,
  63,
  250,
  251,
  252,
  253,
  61,
  7,
  254,
  255,
  256,
  257,
  234,
  20,
  7,
  250,
  251,
  258,
  6,
  259,
  7,
  260,
  261,
  161,
  186,
  110,
  20,
  262,
  251],
 [17, 263, 65, 7, 72, 135, 264, 56, 7, 265, 38, 266, 267, 268, 269, 270],
 [188,
  20,
  7,
  189,
  25,
  271,
  13,
  272,
  15,
  7,
  273,
  274,
  275,
  128,
  121,
  276,
  277,
  6,
  278],
 [188,
  20,
  7,
  189,
  25,
  271,
  13,
  279,
  52,
  280,
  9,
  281,
  6,
  282,
  269,
  283,
  284,
  285,
  6,
  286,
  110,
  287,
  25,
  288,
  20,
  289,
  290],
 [291, 25, 292, 293, 61, 7, 294, 295, 296, 297, 298, 299],
 [1,
  49,
  7,
  300,
  301,
  137,
  20,
  7,
  251,
  65,
  302,
  303,
  13,
  304,
  305,
  257,
  302,
  306,
  6,
  307,
  13,
  308,
  309,
  13,
  310],
 [311,
  6,
  7,
  21,
  312,
  20,
  7,
  189,
  313,
  110,
  81,
  314,
  315,
  316,
  6,
  7,
  317,
  318,
  121,
  276,
  319,
  6,
  320,
  6,
  201],
 [321,
  7,
  322,
  7,
  323,
  267,
  324,
  325,
  6,
  69,
  326,
  9,
  327,
  328,
  329,
  33,
  69,
  326],
 [38, 330, 139, 7, 331, 332, 333, 334, 33, 7, 335, 20, 336, 207],
 [38, 254, 337, 20, 7, 338, 20, 339, 340, 201, 164, 25, 341, 342, 61, 7, 343],
 [17, 41, 42, 344, 189, 7, 21, 38, 345, 346, 347],
 [17,
  144,
  50,
  216,
  179,
  348,
  349,
  350,
  351,
  352,
  353,
  231,
  25,
  354,
  33,
  94,
  355,
  30,
  6,
  12,
  13,
  356,
  357],
 [358, 13, 359, 360, 7, 361, 9, 362, 25, 363, 161, 364, 365, 366],
 [367, 368, 121, 369, 33, 30, 370, 7, 371, 372, 373, 7, 374, 375],
 [376, 121, 7, 377, 378, 20, 229, 21, 379, 30],
 [380, 381, 382, 383, 56, 7, 384, 385, 382, 66, 135, 386, 387, 388, 323],
 [17,
  133,
  2,
  389,
  12,
  65,
  66,
  390,
  391,
  392,
  393,
  33,
  195,
  117,
  11,
  394,
  395,
  396,
  139,
  397],
 [1,
  2,
  398,
  399,
  400,
  401,
  5,
  7,
  402,
  257,
  7,
  403,
  135,
  315,
  404,
  137,
  20,
  405],
 [188, 25, 7, 31, 32, 20, 7, 406, 407],
 [408, 7, 21, 50, 409, 410, 121, 315, 411, 412, 33, 413],
 [380,
  414,
  415,
  416,
  309,
  126,
  417,
  56,
  418,
  419,
  126,
  420,
  421,
  422,
  212,
  423,
  238,
  424,
  425],
 [17, 63, 7, 34, 84, 426, 52, 427, 139, 156, 221, 164, 428, 429, 430],
 [311, 6, 7, 21, 348, 220, 145, 117, 9, 431, 150, 432, 20, 7, 433],
 [17, 63, 380, 434, 435, 49, 212, 436, 437, 215, 438, 439],
 [440,
  441,
  126,
  442,
  443,
  442,
  126,
  444,
  445,
  446,
  447,
  448,
  69,
  110,
  66,
  449,
  450,
  451,
  452],
 [188, 294, 453, 454, 179, 455, 456, 457, 458, 459, 460],
 [17, 63, 7, 406, 84, 426, 52, 150, 461, 462, 9, 463, 464, 465, 61, 7, 221],
 [358,
  7,
  16,
  148,
  466,
  7,
  467,
  468,
  7,
  94,
  469,
  470,
  327,
  20,
  218,
  219,
  20,
  471],
 [188,
  20,
  7,
  189,
  52,
  472,
  99,
  473,
  25,
  474,
  475,
  6,
  7,
  21,
  128,
  476,
  13,
  477,
  478,
  20,
  241,
  472],
 [17,
  9,
  7,
  479,
  480,
  481,
  139,
  482,
  483,
  484,
  483,
  121,
  156,
  208,
  139,
  354,
  186,
  481],
 [408, 7, 21, 50, 144, 216, 485, 63, 486, 61, 487, 488, 489],
 [490,
  491,
  135,
  492,
  61,
  7,
  493,
  13,
  210,
  288,
  353,
  494,
  6,
  495,
  33,
  496,
  497,
  498],
 [188,
  20,
  7,
  189,
  25,
  474,
  475,
  6,
  7,
  21,
  499,
  9,
  273,
  500,
  52,
  501,
  502,
  503],
 [504, 7, 505, 20, 269, 506, 248, 2, 398, 320, 56, 507],
 [499, 466, 268, 7, 508, 509, 510, 511, 20, 7, 177],
 [440,
  512,
  513,
  514,
  7,
  515,
  516,
  517,
  518,
  13,
  519,
  520,
  20,
  521,
  522,
  61,
  130,
  523],
 [321, 524, 9, 525, 30, 526, 527, 528],
 [499, 529, 6, 428, 530, 531, 532, 25, 13, 107, 533, 33, 395],
 [38,
  534,
  20,
  7,
  134,
  61,
  535,
  20,
  7,
  536,
  537,
  538,
  539,
  540,
  30,
  9,
  541,
  542,
  543,
  360,
  544],
 [490,
  7,
  72,
  135,
  545,
  6,
  546,
  7,
  28,
  224,
  201,
  61,
  269,
  547,
  269,
  214,
  2,
  398,
  548,
  13,
  549,
  550,
  6,
  551],
 [311, 6, 7, 21, 312, 20, 7, 189, 25, 190, 552, 553, 201, 554],
 [188,
  20,
  7,
  189,
  555,
  25,
  190,
  556,
  557,
  13,
  283,
  20,
  558,
  110,
  559,
  560,
  212,
  234,
  561],
 [17, 49, 50, 216, 179, 7, 230, 490, 30, 307, 56, 562, 302, 563, 396],
 [17, 63, 229, 21, 84, 564, 565, 566, 567, 568, 569, 56, 201, 570],
 [17,
  571,
  144,
  13,
  572,
  573,
  574,
  145,
  475,
  6,
  7,
  21,
  575,
  576,
  573,
  276,
  577],
 [380, 578, 2, 315, 579, 33, 451, 184, 385, 246, 13, 580, 581],
 [311, 6, 7, 34, 582, 583, 584, 585, 586, 20, 7, 587, 9, 588],
 [17,
  159,
  394,
  193,
  288,
  396,
  314,
  315,
  394,
  589,
  288,
  396,
  590,
  591,
  445,
  126,
  592,
  593,
  594,
  130,
  595,
  52,
  596],
 [597, 598, 387, 599, 600, 61, 601, 602, 603, 6, 269, 604],
 [605, 144, 178, 179, 7, 21, 606, 13, 607, 25, 315, 608, 13, 609, 20, 610],
 [490,
  611,
  612,
  613,
  269,
  614,
  615,
  616,
  398,
  617,
  618,
  6,
  401,
  560,
  13,
  619,
  33,
  13,
  620,
  621],
 [17, 144, 50, 216, 179, 7, 406, 622, 37, 159, 42, 623, 33, 624, 9, 134],
 [38, 31, 32, 33, 229, 21, 76, 42, 126, 126, 17, 605, 625, 626, 61, 627],
 [17, 9, 628, 52, 629, 630, 128, 631, 632, 20, 633, 212, 13, 634, 635],
 [38, 34, 25, 84, 636, 637, 638, 309, 13, 639],
 [17, 9, 7, 31, 32, 20, 7, 21, 150, 634, 640, 179, 641, 45, 642],
 [17,
  49,
  50,
  51,
  52,
  643,
  644,
  645,
  15,
  7,
  345,
  646,
  231,
  647,
  7,
  648,
  283,
  20,
  649],
 [17, 9, 7, 31, 32, 33, 7, 34, 650, 6, 342, 45, 45, 625, 651, 652, 42, 653],
 [38,
  514,
  654,
  655,
  20,
  656,
  657,
  49,
  315,
  12,
  7,
  658,
  6,
  594,
  543,
  657,
  56,
  7,
  553],
 [659,
  200,
  247,
  543,
  117,
  33,
  512,
  660,
  661,
  306,
  543,
  117,
  6,
  216,
  662,
  6,
  394,
  162,
  33,
  170],
 [38, 189, 25, 474, 663, 664, 665, 7, 666, 6, 667, 137, 168, 135, 7, 94, 469],
 [17, 9, 7, 31, 32, 33, 7, 21, 668, 669, 670],
 [376, 671, 7, 672, 38, 673],
 [674, 9, 675, 56, 676, 677, 678, 139, 679],
 [17,
  49,
  50,
  51,
  52,
  680,
  33,
  681,
  231,
  25,
  682,
  33,
  13,
  683,
  684,
  424,
  13,
  685],
 [408, 7, 21, 50, 51, 110, 94, 117, 686, 687, 688],
 [17, 159, 689, 61, 7, 690, 691, 38, 692, 159, 4, 6, 7, 693, 694],
 [695, 174, 696, 52, 697, 698, 531, 302, 246, 398, 699, 532, 56, 700, 701, 80],
 [17, 41, 42, 7, 31, 32, 33, 7, 21, 702, 703, 139, 704],
 [22,
  469,
  479,
  480,
  705,
  139,
  706,
  99,
  705,
  707,
  25,
  110,
  61,
  7,
  705,
  708,
  709,
  25,
  653,
  6,
  7,
  164,
  710,
  711],
 [188, 25, 271, 7, 712, 20, 7, 713, 532, 682, 28, 714, 715, 20, 716],
 [17, 9, 7, 31, 32, 20, 229, 406, 717, 139, 718, 719, 25, 720, 469],
 [38,
  721,
  86,
  20,
  7,
  418,
  20,
  722,
  723,
  466,
  724,
  725,
  726,
  41,
  727,
  387,
  728,
  6,
  729],
 [17, 25, 387, 730, 475, 6, 7, 21, 231, 9, 13, 731, 732],
 [188, 20, 7, 189, 733, 25, 190, 734, 250, 25, 735, 736, 139, 737, 212, 738],
 [1, 2, 7, 361, 278, 6, 739, 740, 6, 69, 200, 213, 231, 41, 42, 741, 139, 742],
 [380,
  743,
  744,
  6,
  745,
  13,
  107,
  573,
  97,
  326,
  746,
  110,
  66,
  745,
  532,
  179,
  13,
  747,
  748,
  543,
  213,
  380,
  743,
  749,
  531,
  66,
  246,
  750,
  751,
  27,
  110,
  747,
  752,
  66,
  353,
  126,
  491,
  753,
  398,
  320,
  754,
  755,
  531,
  756,
  757,
  758,
  759],
 [231, 144, 42, 760, 179, 7, 21, 761, 762, 763, 466, 12, 764, 139, 765, 571],
 [311,
  6,
  766,
  434,
  312,
  20,
  7,
  189,
  767,
  20,
  173,
  25,
  156,
  768,
  6,
  42,
  769,
  499,
  168,
  121,
  770,
  99,
  771],
 [311,
  6,
  7,
  21,
  30,
  428,
  6,
  42,
  772,
  33,
  7,
  189,
  773,
  774,
  233,
  61,
  775,
  776,
  777,
  778,
  25,
  315,
  779],
 [38,
  361,
  780,
  110,
  532,
  25,
  720,
  781,
  6,
  546,
  13,
  782,
  139,
  783,
  109,
  110,
  784,
  785,
  81],
 [188,
  20,
  7,
  189,
  25,
  271,
  474,
  52,
  461,
  30,
  367,
  461,
  529,
  6,
  320,
  6,
  786,
  787,
  61,
  788,
  33,
  789],
 [38,
  72,
  84,
  285,
  6,
  564,
  790,
  791,
  33,
  792,
  6,
  793,
  7,
  794,
  20,
  7,
  118,
  119,
  795],
 [17, 2, 7, 72, 49, 443, 189, 7, 796, 284, 797, 269, 388, 798],
 [17, 25, 7, 31, 32, 20, 7, 21, 407, 9, 433, 688],
 [163,
  2,
  799,
  563,
  56,
  800,
  7,
  801,
  9,
  802,
  291,
  135,
  803,
  804,
  33,
  560,
  6,
  307,
  7,
  805],
 [17, 144, 50, 216, 52, 806, 475, 807, 61, 808, 121, 809, 810, 27, 384],
 [38, 109, 811, 38, 812, 813, 811, 135, 52, 7, 814, 20, 7, 180, 9, 815, 816],
 [188, 25, 7, 31, 32, 20, 229, 21, 659, 817, 56, 163, 6, 68, 15, 203],
 [188,
  20,
  7,
  189,
  164,
  25,
  94,
  768,
  6,
  42,
  818,
  150,
  819,
  820,
  168,
  25,
  557,
  15,
  821],
 [38, 189, 733, 121, 466, 822, 823, 579, 234, 824, 825, 56, 7, 366],
 [311,
  6,
  7,
  21,
  7,
  826,
  126,
  827,
  828,
  126,
  25,
  699,
  829,
  110,
  13,
  173,
  438,
  13,
  720,
  411,
  828],
 [1,
  2,
  7,
  830,
  30,
  831,
  7,
  832,
  309,
  833,
  834,
  284,
  2,
  833,
  110,
  835,
  7,
  30,
  9,
  836],
 [17,
  25,
  7,
  18,
  152,
  33,
  13,
  837,
  9,
  838,
  33,
  839,
  840,
  38,
  837,
  285,
  6,
  42,
  841,
  842,
  139,
  843],
 [17,
  135,
  746,
  52,
  7,
  844,
  20,
  13,
  107,
  584,
  212,
  845,
  38,
  846,
  20,
  7,
  584,
  41,
  847,
  56,
  13,
  848,
  849],
 [17,
  9,
  7,
  850,
  851,
  27,
  13,
  604,
  61,
  852,
  6,
  69,
  164,
  853,
  854,
  855,
  856,
  124],
 [590, 21, 84, 857, 858, 859, 52, 860, 861, 862],
 [38,
  134,
  135,
  136,
  137,
  27,
  863,
  864,
  6,
  865,
  866,
  139,
  867,
  179,
  543,
  868,
  869],
 [1,
  2,
  7,
  361,
  40,
  7,
  210,
  288,
  247,
  33,
  7,
  870,
  215,
  246,
  871,
  833,
  179,
  7,
  872],
 [38,
  873,
  874,
  875,
  306,
  6,
  876,
  7,
  877,
  33,
  491,
  878,
  13,
  879,
  878,
  13,
  874,
  875,
  12,
  7,
  880],
 [188, 20, 7, 189, 25, 271, 474, 38, 881, 25, 882, 27, 7, 883],
 [17, 63, 7, 21, 84, 426, 52, 884, 885, 886, 451, 30, 139, 451, 156, 727, 887],
 [38, 72, 699, 13, 888, 20, 889, 212, 7, 505, 890, 891, 7, 892, 20, 7, 21],
 [893,
  894,
  895,
  20,
  7,
  254,
  412,
  309,
  896,
  897,
  29,
  898,
  20,
  866,
  144,
  286,
  7,
  899,
  20,
  900],
 [17, 901, 144, 81, 739, 6, 854, 902, 903, 61, 904, 905, 724, 906, 907],
 [908,
  7,
  909,
  684,
  443,
  417,
  910,
  6,
  7,
  911,
  7,
  912,
  20,
  7,
  361,
  9,
  913,
  914,
  915],
 [916, 917, 918, 269, 31, 6, 919, 7, 920, 921, 532, 5],
 [17, 144, 50, 216, 52, 922, 499, 435, 12, 6, 923, 33, 13, 924, 238, 925],
 [17, 25, 7, 31, 32, 33, 229, 21, 38, 926, 927, 179, 566, 928, 929],
 [17,
  63,
  930,
  931,
  932,
  6,
  7,
  933,
  934,
  164,
  935,
  219,
  6,
  7,
  936,
  139,
  7,
  887],
 [311, 6, 7, 21, 30, 12, 937, 198, 938, 939],
 [17, 25, 7, 18, 19, 20, 7, 21, 231, 9, 238, 6, 42, 940, 15, 941, 942],
 [943,
  99,
  944,
  9,
  945,
  946,
  110,
  7,
  947,
  20,
  536,
  366,
  61,
  7,
  948,
  949,
  42,
  61,
  7,
  950,
  20,
  7,
  951,
  30],
 [17,
  952,
  953,
  7,
  19,
  20,
  954,
  955,
  206,
  956,
  957,
  61,
  958,
  269,
  959,
  216,
  955],
 [231,
  144,
  42,
  760,
  179,
  7,
  21,
  960,
  201,
  961,
  159,
  548,
  126,
  962,
  126,
  6,
  7,
  963,
  33,
  13,
  964,
  965,
  966],
 [17, 9, 7, 34, 84, 52, 967, 421, 968, 7, 969, 20, 7, 970, 30, 306, 6, 539],
 [38, 21, 25, 84, 971, 972, 99, 973, 974],
 [188,
  20,
  7,
  189,
  975,
  25,
  271,
  13,
  976,
  193,
  475,
  6,
  7,
  21,
  11,
  745,
  234,
  977,
  179,
  13,
  978],
 [38, 126, 979, 980, 126, 981, 110, 253, 99, 982, 983, 164, 144, 984],
 [311,
  6,
  985,
  986,
  987,
  314,
  30,
  988,
  7,
  989,
  990,
  6,
  7,
  991,
  992,
  993,
  257,
  532,
  438,
  156,
  994],
 [1, 2, 7, 361, 995, 137, 7, 859, 11, 996, 30, 20, 130, 997],
 [38, 133, 20, 7, 21, 25, 998, 7, 999, 20, 345, 961, 212, 201, 1000, 1001],
 [17,
  1002,
  1003,
  61,
  1004,
  475,
  6,
  349,
  1005,
  1006,
  899,
  61,
  30,
  9,
  666,
  20,
  360],
 [311, 6, 7, 21, 13, 1007, 1008, 1009, 56, 1010, 1011],
 [17,
  272,
  2,
  1012,
  12,
  212,
  7,
  505,
  20,
  7,
  230,
  215,
  2,
  398,
  51,
  662,
  6,
  1013,
  1014,
  15,
  13,
  924,
  1015],
 [38,
  18,
  19,
  20,
  7,
  21,
  1016,
  159,
  315,
  1017,
  1018,
  1019,
  6,
  394,
  5,
  7,
  1020,
  1021,
  27,
  1022],
 [188,
  20,
  7,
  189,
  25,
  190,
  38,
  1023,
  1024,
  144,
  40,
  1025,
  30,
  139,
  482,
  99,
  1026,
  117],
 [590, 21, 25, 84, 85, 1027, 110, 1028, 1029, 1030, 1031, 1032, 1033],
 [321,
  7,
  21,
  126,
  1034,
  1035,
  126,
  25,
  1036,
  1037,
  168,
  121,
  1038,
  6,
  327,
  139,
  160,
  1039],
 [605, 51, 179, 7, 34, 110, 1040, 13, 720, 924, 360],
 [408, 7, 34, 50, 144, 216, 1041, 76, 1042, 78, 803, 609, 168, 302, 121],
 [38,
  18,
  19,
  20,
  229,
  21,
  226,
  1043,
  130,
  1044,
  20,
  293,
  139,
  791,
  6,
  405,
  532],
 [311, 6, 7, 21, 1045, 1046, 13, 1047, 1018, 778],
 [17, 49, 50, 51, 52, 1048, 284, 135, 1049, 1050],
 [17,
  144,
  50,
  51,
  52,
  126,
  1051,
  99,
  1052,
  126,
  1053,
  179,
  7,
  34,
  128,
  121,
  7,
  1054,
  20,
  13,
  1055,
  1056],
 [188, 20, 7, 189, 25, 190, 1057, 314, 315, 529, 7, 1058],
 [17,
  9,
  7,
  18,
  19,
  20,
  229,
  21,
  1059,
  7,
  1060,
  15,
  651,
  94,
  1061,
  1062,
  1063,
  651,
  207],
 [376, 1064, 720, 1065, 1066],
 [408, 7, 21, 50, 144, 51, 1067, 135, 319, 65, 66, 135, 210],
 [17, 41, 42, 7, 31, 32, 33, 7, 21, 1068, 6, 1069, 669, 1070],
 [38, 21, 135, 377, 1071, 378],
 [17,
  220,
  7,
  361,
  94,
  73,
  1072,
  6,
  426,
  52,
  61,
  7,
  189,
  21,
  17,
  193,
  76,
  1073,
  61,
  846,
  1051,
  99,
  1074],
 [17, 63, 7, 21, 84, 564, 565, 1075, 1076, 52, 1077],
 [1,
  63,
  13,
  1078,
  99,
  1079,
  1080,
  529,
  13,
  1081,
  1079,
  257,
  287,
  1082,
  1083,
  1084,
  1085,
  217,
  1086,
  1087,
  139,
  1064,
  720,
  1088],
 [1089, 25, 1090, 15, 7, 133, 1091, 1092, 1093, 139, 207, 6, 1094, 61, 1095],
 [349,
  1096,
  1097,
  349,
  1098,
  6,
  4,
  6,
  1099,
  1100,
  1101,
  820,
  1102,
  7,
  40,
  20,
  13,
  1103],
 [1104, 7, 164, 278, 7, 1105, 302, 1106, 395, 139, 1107, 543, 1108],
 [188,
  20,
  7,
  189,
  25,
  271,
  13,
  1109,
  7,
  164,
  307,
  179,
  1110,
  1111,
  9,
  1112,
  1113,
  33,
  1114,
  139,
  1115],
 [17,
  25,
  7,
  1116,
  20,
  1117,
  1118,
  20,
  1119,
  318,
  144,
  539,
  1120,
  1121,
  139,
  1122,
  179,
  1123,
  7,
  508],
 [1,
  63,
  1124,
  548,
  7,
  1125,
  20,
  7,
  1126,
  323,
  25,
  1127,
  38,
  1126,
  323,
  671,
  13,
  888,
  20,
  1128,
  1129],
 [17, 9, 7, 31, 32, 20, 7, 21, 1130, 20, 1131, 9, 1132, 1133],
 [1134,
  81,
  49,
  398,
  306,
  6,
  394,
  798,
  15,
  13,
  173,
  168,
  1135,
  1136,
  5,
  1,
  284,
  1082,
  66,
  41,
  1137,
  42,
  1138,
  186,
  1139,
  15,
  81],
 [17, 50, 76, 49, 6, 12, 798, 475, 6, 7, 361, 1140, 7, 177],
 [1141,
  1142,
  1143,
  253,
  310,
  212,
  7,
  1144,
  99,
  1145,
  1146,
  1147,
  1148,
  198,
  13,
  666,
  6,
  1149,
  1150,
  61,
  964,
  238],
 [188, 20, 7, 189, 41, 42, 7, 31, 32, 20, 7, 21, 38, 1151, 20, 360],
 [188,
  1152,
  20,
  1153,
  327,
  63,
  398,
  1154,
  628,
  465,
  1082,
  1155,
  1156,
  1157,
  1158],
 [321, 1159, 1160, 9, 1161, 883, 76, 1162, 1163, 61, 1164, 139, 1165, 938],
 [1166,
  229,
  21,
  7,
  72,
  9,
  18,
  133,
  25,
  1167,
  1168,
  1169,
  1170,
  139,
  234,
  1171,
  1172],
 [1,
  2,
  7,
  72,
  1173,
  1174,
  1175,
  6,
  42,
  193,
  20,
  7,
  31,
  248,
  318,
  314,
  1072,
  512,
  15,
  833,
  130,
  139,
  1176,
  450,
  81,
  144,
  1084,
  42,
  1177,
  20,
  512,
  7,
  1174,
  1175],
 [188,
  20,
  7,
  189,
  733,
  25,
  474,
  475,
  6,
  7,
  21,
  11,
  394,
  162,
  25,
  7,
  1178,
  20,
  1179,
  1180,
  56,
  107,
  688],
 [311, 6, 7, 21, 312, 20, 7, 189, 25, 1181, 318, 1182, 1183, 13, 289, 541],
 [38, 21, 25, 84, 1184, 20, 7, 1185],
 [1,
  63,
  7,
  72,
  548,
  110,
  180,
  139,
  1186,
  320,
  1187,
  257,
  180,
  1188,
  6,
  476,
  543,
  1186,
  27,
  1189,
  5],
 [17, 9, 7, 1190, 20, 1191, 1192, 231, 159, 1193, 13, 1194],
 [311,
  6,
  7,
  21,
  50,
  144,
  216,
  1195,
  278,
  20,
  13,
  1196,
  20,
  7,
  1197,
  159,
  727,
  1198],
 [321, 7, 172, 1199, 667, 13, 1200, 20, 7, 822, 1201, 139, 1202],
 [321,
  126,
  1133,
  1203,
  1204,
  126,
  7,
  117,
  598,
  7,
  1205,
  20,
  234,
  1206,
  286,
  543,
  411,
  1207,
  33,
  7,
  1208,
  1209],
 [38, 31, 32, 33, 229, 21, 1210, 134, 1211],
 [605,
  144,
  216,
  179,
  7,
  34,
  110,
  1212,
  438,
  13,
  411,
  1213,
  1214,
  763,
  1215,
  179,
  1216],
 [231,
  144,
  42,
  760,
  179,
  7,
  21,
  1217,
  1218,
  220,
  315,
  739,
  13,
  738,
  61,
  1219,
  755],
 [38,
  1220,
  666,
  6,
  1221,
  854,
  1222,
  15,
  854,
  31,
  1223,
  25,
  1224,
  6,
  854,
  1223,
  139,
  1225,
  560,
  51,
  854,
  1222],
 [188,
  20,
  7,
  189,
  25,
  315,
  545,
  61,
  1226,
  55,
  20,
  52,
  1227,
  1228,
  61,
  13,
  1229,
  15,
  1230],
 [17,
  159,
  7,
  21,
  94,
  73,
  426,
  52,
  1231,
  1232,
  234,
  1233,
  6,
  1234,
  854,
  1235,
  217,
  1236,
  61,
  107,
  1237,
  775],
 [188, 25, 190, 475, 6, 7, 21, 1140, 20, 7, 177],
 [17, 9, 7, 1238, 20, 126, 659, 117, 526, 398, 1239, 348, 543, 200, 1080, 529],
 [188,
  20,
  7,
  189,
  144,
  42,
  7,
  31,
  32,
  33,
  7,
  21,
  1232,
  1240,
  1241,
  6,
  1242,
  1243],
 [188,
  20,
  7,
  189,
  1244,
  94,
  73,
  1245,
  1246,
  139,
  69,
  1247,
  61,
  1248,
  7,
  1249,
  20,
  1250,
  1251,
  179,
  7,
  254,
  1252,
  1253,
  519,
  1254,
  1255],
 [188,
  20,
  7,
  189,
  41,
  42,
  7,
  31,
  32,
  20,
  7,
  34,
  150,
  1256,
  99,
  1257,
  713,
  1258,
  1077,
  1259,
  1260],
 [188,
  20,
  7,
  189,
  25,
  1261,
  408,
  1262,
  6,
  1263,
  234,
  164,
  1264,
  1087,
  179,
  1265,
  6,

# 4. Next Word Prediction Format

In [12]:
next_word_prediction_data = []

for numerical_sentence in numerical_document:
    for i in range(1, len(numerical_sentence)):
        next_word_prediction_data.append(numerical_sentence[:i+1])

next_word_prediction_data

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5, 6],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 16],
 [17, 9],
 [17, 9, 7],
 [17, 9, 7, 18],
 [17, 9, 7, 18, 19],
 [17, 9, 7, 18, 19, 20],
 [17, 9, 7, 18, 19, 20, 7],
 [17, 9, 7, 18, 19, 20, 7, 21],
 [17, 9, 7, 18, 19, 20, 7, 21, 22],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27, 28],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 [17, 9],
 [17, 9, 7],
 [17, 9, 7, 31],
 [17, 9, 7, 31, 32],
 [17, 9, 7, 31, 32, 33],
 [17, 9, 7, 31, 32, 33, 7],
 [17, 9, 7, 31, 32, 33, 7, 34],
 [17, 9, 7, 31, 32, 33, 7, 34, 35],
 [17, 9, 7, 31, 32, 33, 7, 34, 35, 36],
 [17, 9, 7, 31, 32, 33, 7, 34, 35, 36, 15],
 [17, 9, 7, 31, 32, 33, 7, 34, 35, 36, 15, 37],
 [38, 31],
 [38, 31, 32],
 [38, 31, 32, 20],
 [38, 31, 32, 20, 7],
 [38, 31, 32, 20, 7, 21],
 [38, 31, 32, 20, 7, 21, 39],
 [38, 31, 32, 20, 7, 21, 39, 40],
 [17, 41],
 [17, 41, 42],
 [17, 41, 42, 7],
 [17, 41, 42, 7, 31],
 [17, 41, 42, 7, 31, 32],
 [17, 41, 42, 7, 31, 32, 33],
 [17, 41, 42, 7, 31, 32, 33, 7],
 [17, 41, 42, 7, 31, 32, 33, 7, 34],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44, 45],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44, 45, 46],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44, 45, 46, 47],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44, 45, 46, 47, 48],
 [17, 49],
 [17, 49, 50],
 [17, 49, 50, 51],
 [17, 49, 50, 51, 52],
 [17, 49, 50, 51, 52, 53],
 [17, 49, 50, 51, 52, 53, 54],
 [17, 49, 50, 51, 52, 53, 54, 55],
 [17, 49, 50, 51, 52, 53, 54, 55, 56],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58, 59],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58, 59, 60],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58, 59, 60, 61],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58, 59, 60, 61, 62],
 [17, 63],
 [17, 63, 64],
 [17, 63, 64, 49],
 [17, 63, 64, 49, 65],
 [17, 63, 64, 49, 65, 66],
 [17, 63, 64, 49, 65, 66, 25],
 [17, 63, 64, 49, 65, 66, 25, 15],
 [17, 63, 64, 49, 65, 66, 25, 15, 67],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68, 52],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68, 52, 69],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68, 52, 69, 70],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68, 52, 69, 70, 71],
 [38, 72],
 [38, 72, 73],
 [38, 72, 73, 74],
 [38, 72, 73, 74, 75],
 [38, 72, 73, 74, 75, 76],
 [38, 72, 73, 74, 75, 76, 77],
 [38, 72, 73, 74, 75, 76, 77, 78],
 [38, 72, 73, 74, 75, 76, 77, 78, 79],
 [38, 72, 73, 74, 75, 76, 77, 78, 79, 80],
 [38, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
 [38, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82],
 [38, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
 [38, 21],
 [38, 21, 25],
 [38, 21, 25, 84],
 [38, 21, 25, 84, 85],
 [38, 21, 25, 84, 85, 86],
 [38, 21, 25, 84, 85, 86, 20],
 [38, 21, 25, 84, 85, 86, 20, 7],
 [38, 21, 25, 84, 85, 86, 20, 7, 87],
 [38, 21, 25, 84, 85, 86, 20, 7, 87, 88],
 [38, 21, 25, 84, 85, 86, 20, 7, 87, 88, 89],
 [17, 9],
 [17, 9, 7],
 [17, 9, 7, 31],
 [17, 9, 7, 31, 32],
 [17, 9, 7, 31, 32, 33],
 [17, 9, 7, 31, 32, 33, 7],
 [17, 9, 7, 31, 32, 33, 7, 34],
 [17, 9, 7, 31, 32, 33, 7, 34, 90],
 [17, 9, 7, 31, 32, 33, 7, 34, 90, 9],
 [17, 9, 7, 31, 32, 33, 7, 34, 90, 9, 91],
 [17, 9],
 [17, 9, 92],
 [17, 9, 92, 93],
 [17, 9, 92, 93, 9],
 [17, 9, 92, 93, 9, 94],
 [17, 9, 92, 93, 9, 94, 95],
 [17, 9, 92, 93, 9, 94, 95, 96],
 [17, 9, 92, 93, 9, 94, 95, 96, 97],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20, 102],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20, 102, 103],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20, 102, 103, 104],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20, 102, 103, 104, 105],
 [17, 9],
 [17, 9, 7],
 [17, 9, 7, 106],
 [17, 9, 7, 106, 20],
 [17, 9, 7, 106, 20, 7],
 [17, 9, 7, 106, 20, 7, 107],
 [17, 9, 7, 106, 20, 7, 107, 108],
 [17, 9, 7, 106, 20, 7, 107, 108, 109],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111, 7],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111, 7, 112],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111, 7, 112, 9],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111, 7, 112, 9, 113],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111, 7, 112, 9, 113, 114],
 [17, 9, 7, 106, 20, 7, 107, 108, 109, 110, 111, 7, 112, 9, 113, 114, 115],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117,
  118],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117,
  118,
  119],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117,
  118,
  119,
  61],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117,
  118,
  119,
  61,
  120],
 [1, 121],
 [1, 121, 122],
 [1, 121, 122, 123],
 [1, 121, 122, 123, 124],
 [1, 121, 122, 123, 124, 125],
 [1, 121, 122, 123, 124, 125, 126],
 [1, 121, 122, 123, 124, 125, 126, 127],
 [1, 121, 122, 123, 124, 125, 126, 127, 126],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129, 130],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129, 130, 131],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129, 130, 131, 20],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129, 130, 131, 20, 132],
 [17, 9],
 [17, 9, 7],
 [17, 9, 7, 133],
 [17, 9, 7, 133, 20],
 [17, 9, 7, 133, 20, 7],
 [17, 9, 7, 133, 20, 7, 134],
 [17, 9, 7, 133, 20, 7, 134, 110],
 [17, 9, 7, 133, 20, 7, 134, 110, 135],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137, 27],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137, 27, 138],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137, 27, 138, 139],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137, 27, 138, 139, 69],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137, 27, 138, 139, 69, 140],
 [17, 9, 7, 133, 20, 7, 134, 110, 135, 136, 137, 27, 138, 139, 69, 140, 11],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145,
  7],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145,
  7,
  146],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145,
  7,
  146,
  147],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145,
  7,
  146,
  147,
  148],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144,
  145,
  7,
  146,
  147,
  148,
  149],
 [150, 151],
 [150, 151, 152],
 [150, 151, 152, 33],
 [150, 151, 152, 33, 153],
 [150, 151, 152, 33, 153, 154],
 [150, 151, 152, 33, 153, 154, 6],
 [150, 151, 152, 33, 153, 154, 6, 155],
 [150, 151, 152, 33, 153, 154, 6, 155, 156],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25, 158],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25, 158, 159],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25, 158, 159, 160],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25, 158, 159, 160, 161],
 [150, 151, 152, 33, 153, 154, 6, 155, 156, 157, 25, 158, 159, 160, 161, 162],
 [163, 2],
 [163, 2, 7],
 [163, 2, 7, 164],
 [163, 2, 7, 164, 165],
 [163, 2, 7, 164, 165, 61],
 [163, 2, 7, 164, 165, 61, 7],
 [163, 2, 7, 164, 165, 61, 7, 166],
 [163, 2, 7, 164, 165, 61, 7, 166, 38],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168, 169],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168, 169, 170],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168, 169, 170, 27],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168, 169, 170, 27, 171],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168, 169, 170, 27, 171, 61],
 [163, 2, 7, 164, 165, 61, 7, 166, 38, 167, 168, 169, 170, 27, 171, 61, 7],
 [163,
  2,
  7,
  164,
  165,
  61,
  7,
  166,
  38,
  167,
  168,
  169,
  170,
  27,
  171,
  61,
  7,
  172],
 [163,
  2,
  7,
  164,
  165,
  61,
  7,
  166,
  38,
  167,
  168,
  169,
  170,
  27,
  171,
  61,
  7,
  172,
  99],
 [163,
  2,
  7,
  164,
  165,
  61,
  7,
  166,
  38,
  167,
  168,
  169,
  170,
  27,
  171,
  61,
  7,
  172,
  99,
  173],
 [163,
  2,
  7,
  164,
  165,
  61,
  7,
  166,
  38,
  167,
  168,
  169,
  170,
  27,
  171,
  61,
  7,
  172,
  99,
  173,
  174],
 [163,
  2,
  7,
  164,
  165,
  61,
  7,
  166,
  38,
  167,
  168,
  169,
  170,
  27,
  171,
  61,
  7,
  172,
  99,
  173,
  174,
  175],
 [38, 21],
 [38, 21, 25],
 [38, 21, 25, 84],
 [38, 21, 25, 84, 176],
 [38, 21, 25, 84, 176, 20],
 [38, 21, 25, 84, 176, 20, 7],
 [38, 21, 25, 84, 176, 20, 7, 177],
 [17, 144],
 [17, 144, 50],
 [17, 144, 50, 178],
 [17, 144, 50, 178, 179],
 [17, 144, 50, 178, 179, 7],
 [17, 144, 50, 178, 179, 7, 21],
 [17, 144, 50, 178, 179, 7, 21, 180],
 [17, 144, 50, 178, 179, 7, 21, 180, 181],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183, 20],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183, 20, 184],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183, 20, 184, 185],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183, 20, 184, 185, 186],
 [17, 144, 50, 178, 179, 7, 21, 180, 181, 182, 183, 20, 184, 185, 186, 187],
 [188, 20],
 [188, 20, 7],
 [188, 20, 7, 189],
 [188, 20, 7, 189, 25],
 [188, 20, 7, 189, 25, 190],
 [188, 20, 7, 189, 25, 190, 191],
 [188, 20, 7, 189, 25, 190, 191, 9],
 [188, 20, 7, 189, 25, 190, 191, 9, 192],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28, 193],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28, 193, 20],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28, 193, 20, 7],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28, 193, 20, 7, 194],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28, 193, 20, 7, 194, 20],
 [188, 20, 7, 189, 25, 190, 191, 9, 192, 25, 28, 193, 20, 7, 194, 20, 126],
 [188,
  20,
  7,
  189,
  25,
  190,
  191,
  9,
  192,
  25,
  28,
  193,
  20,
  7,
  194,
  20,
  126,
  195],
 [188,
  20,
  7,
  189,
  25,
  190,
  191,
  9,
  192,
  25,
  28,
  193,
  20,
  7,
  194,
  20,
  126,
  195,
  196],
 [188,
  20,
  7,
  189,
  25,
  190,
  191,
  9,
  192,
  25,
  28,
  193,
  20,
  7,
  194,
  20,
  126,
  195,
  196,
  126],
 [17, 12],
 [17, 12, 197],
 [17, 12, 197, 198],
 [17, 12, 197, 198, 137],
 [17, 12, 197, 198, 137, 52],
 [17, 12, 197, 198, 137, 52, 7],
 [17, 12, 197, 198, 137, 52, 7, 199],
 [17, 12, 197, 198, 137, 52, 7, 199, 20],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139, 7],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139, 7, 201],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139, 7, 201, 56],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139, 7, 201, 56, 117],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139, 7, 201, 56, 117, 9],
 [17, 12, 197, 198, 137, 52, 7, 199, 20, 200, 139, 7, 201, 56, 117, 9, 202],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7,
  201],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7,
  201,
  12],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7,
  201,
  12,
  7],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7,
  201,
  12,
  7,
  204],
 [17,
  12,
  197,
  198,
  137,
  52,
  7,
  199,
  20,
  200,
  139,
  7,
  201,
  56,
  117,
  9,
  202,
  203,
  139,
  7,
  201,
  12,
  7,
  204,
  205],
 [1, 25],
 [1, 25, 206],
 [1, 25, 206, 207],
 [1, 25, 206, 207, 13],
 [1, 25, 206, 207, 13, 208],
 [1, 25, 206, 207, 13, 208, 209],
 [1, 25, 206, 207, 13, 208, 209, 33],
 [1, 25, 206, 207, 13, 208, 209, 33, 13],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211, 99],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211, 99, 212],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211, 99, 212, 99],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211, 99, 212, 99, 213],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211, 99, 212, 99, 213, 214],
 [1, 25, 206, 207, 13, 208, 209, 33, 13, 210, 211, 99, 212, 99, 213, 214, 215],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217,
  218],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217,
  218,
  219],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217,
  218,
  219,
  20],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217,
  218,
  219,
  20,
  69],
 [1,
  25,
  206,
  207,
  13,
  208,
  209,
  33,
  13,
  210,
  211,
  99,
  212,
  99,
  213,
  214,
  215,
  144,
  216,
  217,
  218,
  219,
  20,
  69,
  10],
 [188, 20],
 [188, 20, 7],
 [188, 20, 7, 189],
 [188, 20, 7, 189, 220],
 [188, 20, 7, 189, 220, 42],
 [188, 20, 7, 189, 220, 42, 7],
 [188, 20, 7, 189, 220, 42, 7, 31],
 [188, 20, 7, 189, 220, 42, 7, 31, 32],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33, 7],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33, 7, 21],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33, 7, 21, 221],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33, 7, 21, 221, 222],
 [188, 20, 7, 189, 220, 42, 7, 31, 32, 33, 7, 21, 221, 222, 223],
 [38, 224],
 [38, 224, 6],
 [38, 224, 6, 225],
 [38, 224, 6, 225, 62],
 [38, 224, 6, 225, 62, 226],
 [38, 224, 6, 225, 62, 226, 42],
 [38, 224, 6, 225, 62, 226, 42, 227],
 [38, 224, 6, 225, 62, 226, 42, 227, 6],
 [38, 224, 6, 225, 62, 226, 42, 227, 6, 228],
 [17, 144],
 [17, 144, 50],
 [17, 144, 50, 216],
 [17, 144, 50, 216, 179],
 [17, 144, 50, 216, 179, 229],
 [17, 144, 50, 216, 179, 229, 230],
 [17, 144, 50, 216, 179, 229, 230, 231],
 [17, 144, 50, 216, 179, 229, 230, 231, 9],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232, 6],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232, 6, 233],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232, 6, 233, 15],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232, 6, 233, 15, 234],
 [17, 144, 50, 216, 179, 229, 230, 231, 9, 232, 6, 233, 15, 234, 235],
 [236, 237],
 [236, 237, 212],
 [236, 237, 212, 13],
 [236, 237, 212, 13, 238],
 [236, 237, 212, 13, 238, 239],
 [236, 237, 212, 13, 238, 239, 240],
 [236, 237, 212, 13, 238, 239, 240, 174],
 [236, 237, 212, 13, 238, 239, 240, 174, 56],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241, 242],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241, 242, 139],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241, 242, 139, 61],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241, 242, 139, 61, 241],
 [236, 237, 212, 13, 238, 239, 240, 174, 56, 241, 242, 139, 61, 241, 213],
 [17, 144],
 [17, 144, 50],
 [17, 144, 50, 51],
 [17, 144, 50, 51, 52],
 [17, 144, 50, 51, 52, 7],
 [17, 144, 50, 51, 52, 7, 185],
 [17, 144, 50, 51, 52, 7, 185, 243],
 [17, 144, 50, 51, 52, 7, 185, 243, 244],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7, 21],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7, 21, 245],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7, 21, 245, 246],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7, 21, 245, 246, 6],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7, 21, 245, 246, 6, 247],
 [17, 144, 50, 51, 52, 7, 185, 243, 244, 179, 7, 21, 245, 246, 6, 247, 33],
 [17,
  144,
  50,
  51,
  52,
  7,
  185,
  243,
  244,
  179,
  7,
  21,
  245,
  246,
  6,
  247,
  33,
  248],
 [17,
  144,
  50,
  51,
  52,
  7,
  185,
  243,
  244,
  179,
  7,
  21,
  245,
  246,
  6,

# 5. Left Padding

In [13]:
maxi = 0
for seq in next_word_prediction_data:
    maxi = max(maxi, len(seq))
    
maxi

47

In [14]:
next_word_prediction_data_padded = []
for sequence in next_word_prediction_data:
    next_word_prediction_data_padded.append([0]*(maxi - len(sequence)) + sequence)
    
next_word_prediction_data_padded

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  7,
  16],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24,
  25],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24,
  25,
  26],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24,
  25,
  26,
  27],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  18,
  19,
  20,
  7,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33,
  7,
  34],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33,
  7,
  34,
  35],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33,
  7,
  34,
  35,
  36],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33,
  7,
  34,
  35,
  36,
  15],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  9,
  7,
  31,
  32,
  33,
  7,
  34,
  35,
  36,
  15,
  37],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31,
  32],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31,
  32,
  20],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31,
  32,
  20,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31,
  32,
  20,
  7,
  21],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31,
  32,
  20,
  7,
  21,
  39],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  38,
  31,
  32,
  20,
  7,
  21,
  39,
  40],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22,
  43],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22,
  43,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22,
  43,
  44,
  45],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22,
  43,
  44,
  45,
  46],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22,
  43,
  44,
  45,
  46,
  47],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  41,
  42,
  7,
  31,
  32,
  33,
  7,
  34,
  22,
  43,
  44,
  45,
  46,
  47,
  48],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7,
  57],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7,
  57,
  58],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7,
  57,
  58,
  59],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7,
  57,
  58,
  59,
  60],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7,
  57,
  58,
  59,
  60,
  61],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  7,
  57,
  58,
  59,
  60,
  61,
  62],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  63],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  63,
  64],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,

# 4. Dataloader

In [15]:
import torch

data_tensor = torch.tensor(next_word_prediction_data_padded, dtype=torch.long)
data_tensor

tensor([[   0,    0,    0,  ...,    0,    1,    2],
        [   0,    0,    0,  ...,    1,    2,    3],
        [   0,    0,    0,  ...,    2,    3,    4],
        ...,
        [   0,    0,    0,  ..., 2416,  891, 2417],
        [   0,    0,    0,  ...,  891, 2417, 2418],
        [   0,    0,    0,  ..., 2417, 2418, 2419]])

In [16]:
X = data_tensor[:, :-1]
y = data_tensor[:, -1]

In [17]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomDataset(Dataset):
    def __init__(self, X,y):
        self.X = X
        self.y = y
        
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, index):
        return self.X[index], self.y[index]

In [18]:
dataset = CustomDataset(X,y)

dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [19]:
for ques, ans in dataloader:
    print(ques)
    print(ans)
    break

tensor([[   0,    0,    0,  ...,  311,    6,    7],
        [   0,    0,    0,  ...,   51,   52,    7],
        [   0,    0,    0,  ...,  319,    6,  320],
        ...,
        [   0,    0,    0,  ..., 2296,  378,   20],
        [   0,    0,    0,  ...,   13,  837,    9],
        [   0,    0,    0,  ...,   17,  193,   76]])
tensor([  21,  185,    6,    6,  315, 2351,   25, 2304,  144,   32,    7,  139,
         475, 1207, 1267,  216, 1358,  126,    2,   25,   42,  532, 2355, 2233,
         433, 1108,  566,  395,  141,    7,  838, 1073])

# 5. Model Build

In [20]:
import torch.nn as nn
class QuesAnsRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
        self.rnn = nn.RNN(50,64, batch_first=True)
        self.fc = nn.Linear(64, vocab_size)
        
    def forward(self, question):
        embedding_ques = self.embedding(question)
        hidden_output, final_output = self.rnn(embedding_ques)
        return self.fc(final_output.squeeze(0))

# 6. Train Model

In [21]:
learning_rate = 0.001
epochs = 50

In [22]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [23]:
model = QuesAnsRNN(len(vocab)).to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [24]:
for epoch in range(epochs):
    epochs_loss = 0
    for batch_question, batch_answer in dataloader:
        batch_question, batch_answer = batch_question.to(device), batch_answer.to(device)
        optimizer.zero_grad()
        
        y_pred = model(batch_question)
        
        loss = criterion(y_pred, batch_answer)
        
        loss.backward()
        
        optimizer.step()
        
        epochs_loss += loss.item()
        
    avg_epoch_loss = epochs_loss / len(dataloader)
    print(f"Epoch {epoch+1}: Loss {avg_epoch_loss}")

Epoch 1: Loss 6.827760118666526
Epoch 2: Loss 5.968869533776248
Epoch 3: Loss 5.5779963528961565
Epoch 4: Loss 5.224491659536401
Epoch 5: Loss 4.893950087400888
Epoch 6: Loss 4.580511531394547
Epoch 7: Loss 4.287136377635338
Epoch 8: Loss 4.001420594844581
Epoch 9: Loss 3.733442383683074
Epoch 10: Loss 3.4766373030872266
Epoch 11: Loss 3.2357799462757666
Epoch 12: Loss 3.006864524975852
Epoch 13: Loss 2.7936435378933346
Epoch 14: Loss 2.5924049363591366
Epoch 15: Loss 2.412029300982527
Epoch 16: Loss 2.2468559291847514
Epoch 17: Loss 2.0952442874552304
Epoch 18: Loss 1.9573704113109478
Epoch 19: Loss 1.828470861268736
Epoch 20: Loss 1.7140579836991812
Epoch 21: Loss 1.6083396979882014
Epoch 22: Loss 1.5088552582808055
Epoch 23: Loss 1.4184919751531355
Epoch 24: Loss 1.3323087600751538
Epoch 25: Loss 1.254282747314184
Epoch 26: Loss 1.1832428661124834
Epoch 27: Loss 1.1149582120887471
Epoch 28: Loss 1.0523181490878346
Epoch 29: Loss 0.9950991817035121
Epoch 30: Loss 0.9417755607500116
Epoch 31: Loss 0.891485155123398
Epoch 32: Loss 0.8453890722074944
Epoch 33: Loss 0.8032334615086124
Epoch 34: Loss 0.7638020318820763
Epoch 35: Loss 0.7245192975424137
Epoch 36: Loss 0.6931820421545337
Epoch 37: Loss 0.6623281735725918
Epoch 38: Loss 0.631569469989088
Epoch 39: Loss 0.6060692126325552
Epoch 40: Loss 0.5817711985210166
Epoch 41: Loss 0.5584006406583232
Epoch 42: Loss 0.5384015756894939
Epoch 43: Loss 0.5187175502049972
Epoch 44: Loss 0.5010172223278101
Epoch 45: Loss 0.48357932962075306
Epoch 46: Loss 0.46912556497140545
Epoch 47: Loss 0.4534009295627784
Epoch 48: Loss 0.44181169841546736
Epoch 49: Loss 0.43031442641469947
Epoch 50: Loss 0.4189213501961894

# 7. Inference

In [25]:
def predict(question, threshold=0.5, words=1):
    # tokenize 
    tokens = word_tokenize(question.lower())
    
    # convert text to number
    numerical_question = line_to_numeric_rep(question, vocab)
    
    # padding
    numerical_question_padded = [0]*(maxi - len(numerical_question)) + numerical_question
    
    # make it tensor (push into gpu)
    tensor_question = torch.tensor(numerical_question_padded, dtype=torch.long).unsqueeze(0).to(device)
    
    # probabilities
    output_probability = model(tensor_question)
    
    # use softmax
    probs = torch.nn.functional.softmax(output_probability, dim=1)
    
    # get max probs
    max_probs, max_indexes = torch.topk(probs,k=words, dim=1)
    
    inverse_vocab = {value:key for key, value in vocab.items()}
    
    response = {
        "Ans" : "",
        "confidence" : []
    }

    for prob, index in zip(max_probs[0], max_indexes[0]):

        response['Ans'] += inverse_vocab[index.item()]
        response['Ans'] += " "
        response['confidence'].append(round(prob.item(), 4))
    
    return response['Ans'], response['confidence']

In [26]:
predict("Jane Armstrong",words=5, threshold=0.5)

('in after that learn which ', [0.4519, 0.186, 0.0598, 0.0501, 0.0363])

In [27]:
df

,question,answer_text
20799,Why did Sue come up to the instructor 's family ?,To have a chat with the couple .
15226,What 's the main idea of the passage ?,An endangered language is spoken by only two p...
12458,What 's the best title for the text ?,Lunches packed with love .
22099,The best title of the passage is,Passing help
27284,What would be the best title for the text ?,An Unusual Architect -- Ieoh Ming Pei
...,...,...
30757,What did Rohm do when she saw the two boys ?,She asked them to ask their parents for help .
11029,We can learn from the passage that,the girl has played ping - pong many times
27722,Hybrid cars consume less energy than conventio...,have electric power to assist when needed
22967,The title of the passage should be,Short stature and short life
16631,Which of the following is NOT ture about Edwar...,He ran himself into exhaustion delivering pape...